### ISSUE TITLE
face dataset result bad

### ISSUE THREAD

**Issue by ForrestPi** [za-cheng/WildLight#7]
I tried  the face dataset but the result is so bad.
```
python exp_runner.py --case face --conf confs/real.conf --mode train --download_dataset
python exp_runner.py --case face --conf confs/real.conf --mode validate_mesh --is_continue
python exp_runner.py --case face --conf confs/real.conf --mode validate_image --is_continue
```
![face](https://github.com/za-cheng/WildLight/assets/12846142/31b70fae-199f-4b62-8fbe-89908bb2bf9c)

could you give me some tips?

**Comment by za-cheng** [comment]
Hi,

This is likely due to a bad random initialisation of SDF network which should happen very occasionally. The simplest solution is to start another run and most likely you should get much better results; or you can start from e.g. sphere or visual hull, if you want to be absolutely sure.

For reference below is the result I got after 1 hour traning.

Best 
Ziang

![snapshot00](https://github.com/za-cheng/WildLight/assets/57708879/ee586aed-6b62-42e4-b11c-94a9c8631b93)

**Comment by za-cheng** [comment]
closing as resolved. you're welcome to reopen it if issue persists
